--Insertion des genres appartenant à Blues
insert into Genres (name) values ('Blues');
insert into Genres (name, parent_id) values ('Blues rock', 1);
insert into Genres (name, parent_id) values ('Country blues', 1);
insert into Genres (name, parent_id) values ('Jazz blues', 1);
insert into Genres (name, parent_id) values ('Piano blues', 1);
insert into Genres (name, parent_id) values ('Soul blues', 1);
--Insertion des genres appartenant à Easy Listening
insert into Genres (name) values ('Easy Listening');
insert into Genres (name, parent_id) values ('Background music', 7);
insert into Genres (name, parent_id) values ('Beautiful music', 7);
insert into Genres (name, parent_id) values ('Lounge music', 7);
insert into Genres (name, parent_id) values ('New-age music', 7);
--Insertion des genres appartenant à Electronic
insert into Genres (name) values ('Electronic');
insert into Genres (name, parent_id) values ('Ambient', 12);
insert into Genres (name, parent_id) values ('Asian Underground', 12);
insert into Genres (name, parent_id) values ('Breakbeat', 12);
insert into Genres (name, parent_id) values ('Chiptune', 12);
insert into Genres (name, parent_id) values ('Disco', 12);
insert into Genres (name, parent_id) values ('Downtempo', 12);
insert into Genres (name, parent_id) values ('Drum and bass', 12);
insert into Genres (name, parent_id) values ('Electro', 12);
insert into Genres (name, parent_id) values ('Electroacoustic', 12);
insert into Genres (name, parent_id) values ('Electronica', 12);
insert into Genres (name, parent_id) values ('Electronic rock', 12);
insert into Genres (name, parent_id) values ('Hardcore/Hard dance', 12);
insert into Genres (name, parent_id) values ('House', 12);
insert into Genres (name, parent_id) values ('Industrial', 12);
insert into Genres (name, parent_id) values ('Progressive', 12);
insert into Genres (name, parent_id) values ('Techno', 12);
insert into Genres (name, parent_id) values ('Trance', 12);
--Insertion des genres appartenant à Folk
insert into Genres (name) values ('Folk');
insert into Genres (name, parent_id) values ('Contemporary folk', 30);
insert into Genres (name, parent_id) values ('Celtic music', 30);
insert into Genres (name, parent_id) values ('Indie folk', 30);
insert into Genres (name, parent_id) values ('Neofolk', 30);
insert into Genres (name, parent_id) values ('Progressive folk', 30);
insert into Genres (name, parent_id) values ('Industrial folk', 30);
insert into Genres (name, parent_id) values ('Techno-folk', 30);
insert into Genres (name, parent_id) values ('Psychedelic folk', 30);
insert into Genres (name, parent_id) values ('Sung poetry', 30);
insert into Genres (name, parent_id) values ('Cowboy/Western music', 30);
--Insertion des genres appartenant à Hip hop
insert into Genres (name) values ('Hip hop');
insert into Genres (name, parent_id) values ('Crunkcore', 41);
insert into Genres (name, parent_id) values ('Freestyle music', 41);
insert into Genres (name, parent_id) values ('Freestyle rap', 41);
insert into Genres (name, parent_id) values ('G-Funk', 41);
insert into Genres (name, parent_id) values ('Gangsta rap', 41);
insert into Genres (name, parent_id) values ('Grime', 41);
insert into Genres (name, parent_id) values ('Hip pop', 41);
insert into Genres (name, parent_id) values ('Industrial hip hop', 41);
insert into Genres (name, parent_id) values ('Instrumental hip hop', 41);
insert into Genres (name, parent_id) values ('Jazz rap', 41);
insert into Genres (name, parent_id) values ('Ragga', 41);
insert into Genres (name, parent_id) values ('Reggaeton', 41);
insert into Genres (name, parent_id) values ('Rap rock', 41);
insert into Genres (name, parent_id) values ('Trap', 41);
insert into Genres (name, parent_id) values ('Trip hop', 41);
insert into Genres (name, parent_id) values ('Turntablism', 41);
insert into Genres (name, parent_id) values ('Underground hip hop', 41);
--Insertion des genres appartenant à Jazz
insert into Genres (name) values ('Jazz');
insert into Genres (name, parent_id) values ('Acid jazz', 59);
insert into Genres (name, parent_id) values ('Avant-garde jazz', 59);
insert into Genres (name, parent_id) values ('Free improvisation', 59);
insert into Genres (name, parent_id) values ('Gypsy jazz', 59);
insert into Genres (name, parent_id) values ('Hard bop', 59);
insert into Genres (name, parent_id) values ('Jazz fusion', 59);
insert into Genres (name, parent_id) values ('Latin jazz', 59);
insert into Genres (name, parent_id) values ('Modal jazz', 59);
insert into Genres (name, parent_id) values ('Neo-bop jazz', 59);
insert into Genres (name, parent_id) values ('Neo-swing', 59);
insert into Genres (name, parent_id) values ('Novelty ragtime', 59);
insert into Genres (name, parent_id) values ('Nu jazz', 59);
insert into Genres (name, parent_id) values ('Orchestral jazz', 59);
insert into Genres (name, parent_id) values ('Smooth jazz', 59);
insert into Genres (name, parent_id) values ('Swing', 59);
insert into Genres (name, parent_id) values ('Vocal jazz', 59);
--Insertion des genres appartenant à Rock
insert into Genres (name) values ('Rock');
insert into Genres (name, parent_id) values ('Alternative rock', 76);
insert into Genres (name, parent_id) values ('Grunge', 76);
insert into Genres (name, parent_id) values ('Indie rock', 76);
insert into Genres (name, parent_id) values ('Nu metal', 76);
insert into Genres (name, parent_id) values ('Hard rock', 76);
insert into Genres (name, parent_id) values ('Heavy metal', 76);
insert into Genres (name, parent_id) values ('Alternative metal', 76);
insert into Genres (name, parent_id) values ('Black metal', 76);
insert into Genres (name, parent_id) values ('Death metal', 76);
insert into Genres (name, parent_id) values ('Doom metal', 76);
insert into Genres (name, parent_id) values ('Metalcore', 76);
insert into Genres (name, parent_id) values ('Deathcore', 76);
insert into Genres (name, parent_id) values ('Progressive metal', 76);
insert into Genres (name, parent_id) values ('Djent', 76);
insert into Genres (name, parent_id) values ('Rap metal', 76);
insert into Genres (name, parent_id) values ('Speed metal', 76);
insert into Genres (name, parent_id) values ('Stoner rock', 76);
insert into Genres (name, parent_id) values ('Symphonic metal', 76);
insert into Genres (name, parent_id) values ('Thrash metal', 76);
insert into Genres (name, parent_id) values ('Jazz rock', 76);
insert into Genres (name, parent_id) values ('Pop rock', 76);
insert into Genres (name, parent_id) values ('Progressive rock', 76);
insert into Genres (name, parent_id) values ('Psychedelic rock', 76);
insert into Genres (name, parent_id) values ('Deathrock', 76);
insert into Genres (name, parent_id) values ('Grindcore', 76);
insert into Genres (name, parent_id) values ('Emo', 76);
insert into Genres (name, parent_id) values ('Punk', 76);
