drop table Join_Band_Users
drop table Join_Band_Genre
drop table Join_Users_Instrument
drop table Join_Users_Genre
drop table users;
drop table bands;
drop table instruments;
drop table genres;

create table Users(
UserId int IDENTITY(1,1) Primary key,
FirstName NVARCHAR(100) NOT NULL,
LastName NVARCHAR(100) NOT NULL,
BirthDate DATETIME NOT NULL,
Nickname NVARCHAR(100) NOT NULL,
Email NVARCHAR(100) NOT NULL,
Password NVARCHAR(100) NOT NULL,
Location NVARCHAR(100) NOT NULL,
Description text null,
Photo varbinary(max),
Gender NVARCHAR(100),
Latitude FLOAT(40),
Longitude FLOAT(40)
);
create table Bands(
BandId int IDENTITY(1,1) Primary key,
Name NVARCHAR(50) not null,
Description text null,
Location NVARCHAR(100) NOT NULL
);
create table Instruments(
InstrumentId int IDENTITY(1,1) Primary Key,
Name NVARCHAR(50) not null
);
create table Genres(
GenreId int IDENTITY(1,1) Primary Key,
Name NVARCHAR(50) not null
);
create table Event(
EventId int IDENTITY(1,1) Primary key,
EventName NVARCHAR(100) NOT NULL,
EventLocation NVARCHAR(100) NOT NULL,
EventAddress NVARCHAR(100) NOT NULL,
EventCity NVARCHAR(100) NOT NULL,
EventDate datetime NOT NULL,
EventMaxAudience NVARCHAR(100) NOT NULL,
EventSalary float(10) NOT NULL,
EventGender NVARCHAR(100) not null,
EventStageSize int,
EventPhoto varbinary(max),
EventCreator NVARCHAR(100)
);
create table Join_Users_Genre(
UserId int REFERENCES Users(UserId) not null,
GenreId int REFERENCES Genres(GenreId) not null,
constraint pk_join_Users_genre Primary Key (UserId, GenreId)
);
create table Join_Users_Instrument(
UserId int REFERENCES Users(UserId) not null,
InstrumentId int REFERENCES Instruments(InstrumentId) not null,
Skills int not null,
constraint pk_join_users_instrument primary key (UserId, InstrumentId)
);
create table Join_Band_Genre(
BandId int REFERENCES Bands(BandId) not null,
GenreId int REFERENCES Genres(GenreId) not null,
constraint pk_join_band_genre Primary Key (BandId, GenreId)
);
create table Join_Band_Users(
BandId int REFERENCES Bands(BandId) not null,
UserId int REFERENCES Users(UserId) not null,
constraint pk_join_band_user Primary Key (BandId, UserId)
);
create table Advert(
AdvertId int IDENTITY(1,1) Primary key,
Type NVARCHAR(100) NOT NULL,
Creator int FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
GenresAdvert int FOREIGN KEY REFERENCES Genres(GenreId) NOT NULL,
Description NVARCHAR(max) NOT NULL,
Status nvarchar(100) NOT NULL,
CreationDate DATETIME NOT NULL,
ExpirationDate DATETIME NOT NULL,
Location NVARCHAR(100),
AdvertPhoto varbinary(max),
);
insert into Bands(Name, Description, Location)
values('The wild Mofos', 'We are the Wild Mofos and we fear nothing, even your mom', 'Las Vegas');
insert into Bands(Name, Description, Location)
values('Loss Sanchez', 'Lost in the desert cooking pancakes!', 'Unknown');
insert into Genres(Name) values ('Metal');
insert into Genres(Name) values ('Rock');
insert into Genres(Name) values ('Classique');
insert into Genres(Name) values ('Jazz');
insert into Genres(Name) values ('Chuck Norris Style');
insert into Instruments(Name) Values('Aucun');
insert into Instruments (Name) values('Aboès');
insert into Instruments (Name) values('Accordéon');
insert into Instruments (Name) values('Accordina');
insert into Instruments (Name) values('Acordo');
insert into Instruments (Name) values('Adjalin');
insert into Instruments (Name) values('Aérophon');
insert into Instruments (Name) values('Agogô ');
insert into Instruments (Name) values('Alboka');
insert into Instruments (Name) values('Allun');
insert into Instruments (Name) values('Alto');
insert into Instruments (Name) values('Ampongabe');
insert into Instruments (Name) values('Angklung');
insert into Instruments (Name) values('Antsiva ');
insert into Instruments (Name) values('Appeau');
insert into Instruments (Name) values('Archicistre');
insert into Instruments (Name) values('Archiluth');
insert into Instruments (Name) values('Arghoul');
insert into Instruments (Name) values('Atabal ');
insert into Instruments (Name) values('Atabaque ');
insert into Instruments (Name) values('Atranatrana ');
insert into Instruments (Name) values('Autoharpe');
insert into Instruments (Name) values('Azina');
insert into Instruments (Name) values('Baglama');
insert into Instruments (Name) values('Bagpipe ');
insert into Instruments (Name) values('Balafon');
insert into Instruments (Name) values('Balalaïka');
insert into Instruments (Name) values('Bandola');
insert into Instruments (Name) values('Bandonéon');
insert into Instruments (Name) values('Bandourka ');
insert into Instruments (Name) values('Bandura ');
insert into Instruments (Name) values('Bangdi');
insert into Instruments (Name) values('Banjo');
insert into Instruments (Name) values('Banshrî ');
insert into Instruments (Name) values('Barâtaka ');
insert into Instruments (Name) values('Barbitos');
insert into Instruments (Name) values('Baryton');
insert into Instruments (Name) values('Basse quatre cylindres');
insert into Instruments (Name) values('Bassethorn');
insert into Instruments (Name) values('Basson');
insert into Instruments (Name) values('Batá ');
insert into Instruments (Name) values('Bâton de pluie');
insert into Instruments (Name) values('Batterie');
insert into Instruments (Name) values('Batterie électronique');
insert into Instruments (Name) values('Batyphon');
insert into Instruments (Name) values('Bawoo ');
insert into Instruments (Name) values('Bayan ');
insert into Instruments (Name) values('Bazantar ');
insert into Instruments (Name) values('Béchonnet ');
insert into Instruments (Name) values('Belek ');
insert into Instruments (Name) values('Bendir ');
insert into Instruments (Name) values('Bendré ');
insert into Instruments (Name) values('Benju');
insert into Instruments (Name) values('Berimbau');
insert into Instruments (Name) values('Biniou ');
insert into Instruments (Name) values('Birbyne ');
insert into Instruments (Name) values('Bitu-uvu ');
insert into Instruments (Name) values('Biva');
insert into Instruments (Name) values('Biwa ');
insert into Instruments (Name) values('Bobre');
insert into Instruments (Name) values('Bodega ');
insert into Instruments (Name) values('Bodhrán ');
insert into Instruments (Name) values('Boha ');
insert into Instruments (Name) values('Bomba ');
insert into Instruments (Name) values('Bombarde');
insert into Instruments (Name) values('Bombardon');
insert into Instruments (Name) values('Bombo ');
insert into Instruments (Name) values('Bongo');
insert into Instruments (Name) values('Bourdon');
insert into Instruments (Name) values('Bouzouki');
insert into Instruments (Name) values('Bratsch violon à 3 cordes roumain');
insert into Instruments (Name) values('Bugle');
insert into Instruments (Name) values('Bugle ');
insert into Instruments (Name) values('Bugle ');
insert into Instruments (Name) values('Buhai ');
insert into Instruments (Name) values('Bulbultara ');
insert into Instruments (Name) values('Cabassa');
insert into Instruments (Name) values('Cabrette ');
insert into Instruments (Name) values('Cài ban nhac');
insert into Instruments (Name) values('Cài chuong chua');
insert into Instruments (Name) values('Cài dan nha tro');
insert into Instruments (Name) values('Cài kèn dôi');
insert into Instruments (Name) values('Cài-nhi');
insert into Instruments (Name) values('Caisse claire');
insert into Instruments (Name) values('Caisse ');
insert into Instruments (Name) values('Caisse roulante');
insert into Instruments (Name) values('Caixa ');
insert into Instruments (Name) values('Cajón ');
insert into Instruments (Name) values('Calebasse');
insert into Instruments (Name) values('Çaradiya-vina');
insert into Instruments (Name) values('Carémère');
insert into Instruments (Name) values('Carillon');
insert into Instruments (Name) values('Carillon de fanfare');
insert into Instruments (Name) values('Carnyx');
insert into Instruments (Name) values('Castagnettes');
insert into Instruments (Name) values('Çauktika-vina');
insert into Instruments (Name) values('Caval ');
insert into Instruments (Name) values('Cavaquinho');
insert into Instruments (Name) values('Caxixi');
insert into Instruments (Name) values('Célesta');
insert into Instruments (Name) values('Cellulophone');
insert into Instruments (Name) values('Chabrette ');
insert into Instruments (Name) values('Chalemie');
insert into Instruments (Name) values('Chalumeau');
insert into Instruments (Name) values('Chang-kou');
insert into Instruments (Name) values('Chapeau chinois');
insert into Instruments (Name) values('Chapey');
insert into Instruments (Name) values('Charango ');
insert into Instruments (Name) values('Cheipour');
insert into Instruments (Name) values('Chitarrone');
insert into Instruments (Name) values('Chkacheks');
insert into Instruments (Name) values('Choro');
insert into Instruments (Name) values('Choron ');
insert into Instruments (Name) values('Cialamella');
insert into Instruments (Name) values('Cistre');
insert into Instruments (Name) values('Cistre français ');
insert into Instruments (Name) values('Cistre japonais ');
insert into Instruments (Name) values('Cithare');
insert into Instruments (Name) values('Cithare anglaise');
insert into Instruments (Name) values('Cithare japonaise');
insert into Instruments (Name) values('Citole chinoise');
insert into Instruments (Name) values('Clairon');
insert into Instruments (Name) values('Clarinette');
insert into Instruments (Name) values('Clarinette basse');
insert into Instruments (Name) values('Clavecin ');
insert into Instruments (Name) values('Claves');
insert into Instruments (Name) values('Clavicorde ');
insert into Instruments (Name) values('Clavicytherium ');
insert into Instruments (Name) values('Clavinet');
insert into Instruments (Name) values('Clavi harp');
insert into Instruments (Name) values('Cloche');
insert into Instruments (Name) values('Cloches de bois');
insert into Instruments (Name) values('Cloches tubulaires');
insert into Instruments (Name) values('Cobza ');
insert into Instruments (Name) values('Colachon ');
insert into Instruments (Name) values('Collier de grelots');
insert into Instruments (Name) values('Concertina');
insert into Instruments (Name) values('Congas ');
insert into Instruments (Name) values('Conque ');
insert into Instruments (Name) values('Contrebasse à cordes');
insert into Instruments (Name) values('Contrebasse à vent');
insert into Instruments (Name) values('Contrebasson');
insert into Instruments (Name) values('Cor à pistons');
insert into Instruments (Name) values('Cor anglais');
insert into Instruments (Name) values('Cor de basset');
insert into Instruments (Name) values('Cor de chasse');
insert into Instruments (Name) values('Cor des Alpes');
insert into Instruments (Name) values('Cor naturel');
insert into Instruments (Name) values('Cornamuse');
insert into Instruments (Name) values('Corne');
insert into Instruments (Name) values('Corne de brume');
insert into Instruments (Name) values('Cornemuse');
insert into Instruments (Name) values('Cornet à bouquin');
insert into Instruments (Name) values('Cornet à pistons');
insert into Instruments (Name) values('Cornu');
insert into Instruments (Name) values('Cosmophone');
insert into Instruments (Name) values('Courtaud');
insert into Instruments (Name) values('Cow antler');
insert into Instruments (Name) values('Cow bells ');
insert into Instruments (Name) values('Cristal Baschet');
insert into Instruments (Name) values('Cromorne ');
insert into Instruments (Name) values('Crouth');
insert into Instruments (Name) values('Cuatro ');
insert into Instruments (Name) values('Cuica ');
insert into Instruments (Name) values('Cumbus');
insert into Instruments (Name) values('Cura ');
insert into Instruments (Name) values('Cymbale antique');
insert into Instruments (Name) values('Cymbales');
insert into Instruments (Name) values('Cymbalum');
insert into Instruments (Name) values('Dabakan ');
insert into Instruments (Name) values('Daf');
insert into Instruments (Name) values('Dâmâna');
insert into Instruments (Name) values('Danbolino');
insert into Instruments (Name) values('Danhoun');
insert into Instruments (Name) values('Danyen');
insert into Instruments (Name) values('Dap ');
insert into Instruments (Name) values('Darbouka');
insert into Instruments (Name) values('Darvyra');
insert into Instruments (Name) values('Def ');
insert into Instruments (Name) values('Dehol ');
insert into Instruments (Name) values('Diapason');
insert into Instruments (Name) values('Didgeridoo ');
insert into Instruments (Name) values('Dimplito ');
insert into Instruments (Name) values('Dízi ');
insert into Instruments (Name) values('Djembé');
insert into Instruments (Name) values('Djozé');
insert into Instruments (Name) values('Doedelzak');
insert into Instruments (Name) values('Dolcian');
insert into Instruments (Name) values('Domra');
insert into Instruments (Name) values('Dòngxiao ');
insert into Instruments (Name) values('Dou-co');
insert into Instruments (Name) values('Doudouçaine ');
insert into Instruments (Name) values('Doudouk ');
insert into Instruments (Name) values('Doutara');
insert into Instruments (Name) values('Dubreq Stylophone ');
insert into Instruments (Name) values('Duda ');
insert into Instruments (Name) values('Dulcimer');
insert into Instruments (Name) values('Dulcitone');
insert into Instruments (Name) values('Dulzaina');
insert into Instruments (Name) values('Dum dum');
insert into Instruments (Name) values('Egg shaker');
insert into Instruments (Name) values('Eka-tantrika');
insert into Instruments (Name) values('Eka-tara');
insert into Instruments (Name) values('Épinette ');
insert into Instruments (Name) values('Épinette des Vosges');
insert into Instruments (Name) values('Erh-hou-hou');
insert into Instruments (Name) values('Erh-huang-hou');
insert into Instruments (Name) values('Erhu');
insert into Instruments (Name) values('Esrar');
insert into Instruments (Name) values('Estive');
insert into Instruments (Name) values('Euphonium');
insert into Instruments (Name) values('Fa-haotong');
insert into Instruments (Name) values('Fakroum');
insert into Instruments (Name) values('Fango-fango ');
insert into Instruments (Name) values('Fifre');
insert into Instruments (Name) values('Flabiol ');
insert into Instruments (Name) values('Flageolet');
insert into Instruments (Name) values('Fläute de Behaigne ');
insert into Instruments (Name) values('Flaviol');
insert into Instruments (Name) values('Flexatone');
insert into Instruments (Name) values('Fluierul mic ');
insert into Instruments (Name) values('Flûte à bec');
insert into Instruments (Name) values('Flûte à bec double');
insert into Instruments (Name) values('Flûte béarnaise');
insert into Instruments (Name) values('Flûte de Pan');
insert into Instruments (Name) values('Flûte de saule');
insert into Instruments (Name) values('Flûte en sol');
insert into Instruments (Name) values('Flûte harmonique');
insert into Instruments (Name) values('Flûte irlandaise');
insert into Instruments (Name) values('Flûte traversière');
insert into Instruments (Name) values('Forte');
insert into Instruments (Name) values('Foulé');
insert into Instruments (Name) values('Foyera');
insert into Instruments (Name) values('Frestel');
insert into Instruments (Name) values('Fujara');
insert into Instruments (Name) values('Gadoulka');
insert into Instruments (Name) values('Gaïda ');
insert into Instruments (Name) values('Gaita ');
insert into Instruments (Name) values('Gaita gallega ');
insert into Instruments (Name) values('Galoubet');
insert into Instruments (Name) values('Gambri');
insert into Instruments (Name) values('Gamelan');
insert into Instruments (Name) values('Ganibri');
insert into Instruments (Name) values('Gankeke');
insert into Instruments (Name) values('Ganza');
insert into Instruments (Name) values('Gardon ');
insert into Instruments (Name) values('Gasbâ ');
insert into Instruments (Name) values('Gassaa');
insert into Instruments (Name) values('Geige');
insert into Instruments (Name) values('Gemshorn ');
insert into Instruments (Name) values('Gendang-boeleo');
insert into Instruments (Name) values('Gheteh ');
insert into Instruments (Name) values('Gig');
insert into Instruments (Name) values('Gigue');
insert into Instruments (Name) values('Girine');
insert into Instruments (Name) values('Gita ');
insert into Instruments (Name) values('Glassharmonica');
insert into Instruments (Name) values('Glockenspiel');
insert into Instruments (Name) values('Gnaccara');
insert into Instruments (Name) values('Gong');
insert into Instruments (Name) values('Gongsa');
insert into Instruments (Name) values('Gonkogui');
insert into Instruments (Name) values('Gopi-yantra');
insert into Instruments (Name) values('Gota ');
insert into Instruments (Name) values('Goto');
insert into Instruments (Name) values('Graïle ');
insert into Instruments (Name) values('Grelots');
insert into Instruments (Name) values('Grosse caisse');
insert into Instruments (Name) values('Guedra');
insert into Instruments (Name) values('Guimbarde');
insert into Instruments (Name) values('Guiro');
insert into Instruments (Name) values('Guitare');
insert into Instruments (Name) values('Guitare acoustique');
insert into Instruments (Name) values('Guitare basse');
insert into Instruments (Name) values('Guitare électrique');
insert into Instruments (Name) values('Guitare folk');
insert into Instruments (Name) values('Guitare mauresque');
insert into Instruments (Name) values('Guitarra ');
insert into Instruments (Name) values('Guitarron');
insert into Instruments (Name) values('Guiterne');
insert into Instruments (Name) values('Guqin ');
insert into Instruments (Name) values('Gusli');
insert into Instruments (Name) values('Gut-komm');
insert into Instruments (Name) values('Guzheng ');
insert into Instruments (Name) values('Guzla ');
insert into Instruments (Name) values('Hackbrett');
insert into Instruments (Name) values('Halam sénégalais');
insert into Instruments (Name) values('Hangdoung');
insert into Instruments (Name) values('Hang');
insert into Instruments (Name) values('Hapetan de Sumatra');
insert into Instruments (Name) values('Hardingfele');
insert into Instruments (Name) values('Harmonica ');
insert into Instruments (Name) values('Harmonica à bouche');
insert into Instruments (Name) values('Harmonica à lames de verre');
insert into Instruments (Name) values('Harmonica à clavier');
insert into Instruments (Name) values('Harmonicor');
insert into Instruments (Name) values('Harmoniflûte');
insert into Instruments (Name) values('Harmonino');
insert into Instruments (Name) values('Harmonium ');
insert into Instruments (Name) values('Harpe ');
insert into Instruments (Name) values('Harpe à pédales');
insert into Instruments (Name) values('Harpe celtique');
insert into Instruments (Name) values('Harpe chinoise');
insert into Instruments (Name) values('Harpe des Pahouins');
insert into Instruments (Name) values('Harpe égyptienne');
insert into Instruments (Name) values('Harpu ');
insert into Instruments (Name) values('Hautbois');
insert into Instruments (Name) values('Hautbois à capsule');
insert into Instruments (Name) values('Heang-teih');
insert into Instruments (Name) values('Heckelphone');
insert into Instruments (Name) values('Hegelung');
insert into Instruments (Name) values('Hélicon');
insert into Instruments (Name) values('Héliophone');
insert into Instruments (Name) values('Hiachi-riki');
insert into Instruments (Name) values('Hochet');
insert into Instruments (Name) values('Hochet à grelots');
insert into Instruments (Name) values('Horn bugle');
insert into Instruments (Name) values('Hornpipe ');
insert into Instruments (Name) values('Huayllaca');
insert into Instruments (Name) values('Húqín ');
insert into Instruments (Name) values('Hwang chong tché');
insert into Instruments (Name) values('Hwang-teih');
insert into Instruments (Name) values('Ichigenkin');
insert into Instruments (Name) values('Inanga');
insert into Instruments (Name) values('Ingomba');
insert into Instruments (Name) values('Insibi');
insert into Instruments (Name) values('Jabisen');
insert into Instruments (Name) values('Jagajhampa');
insert into Instruments (Name) values('Jaleika ');
insert into Instruments (Name) values('Jamblock');
insert into Instruments (Name) values('Jarana');
insert into Instruments (Name) values('Jejy voatavo');
insert into Instruments (Name) values('Jenbe ');
insert into Instruments (Name) values('Jeu de timbre');
insert into Instruments (Name) values('Jouhikko');
insert into Instruments (Name) values('Ka ');
insert into Instruments (Name) values('Kabosse ');
insert into Instruments (Name) values('Kacapi');
insert into Instruments (Name) values('Kacha-vînâbossy');
insert into Instruments (Name) values('Kachapî-vînâ');
insert into Instruments (Name) values('Kagoura-fouye');
insert into Instruments (Name) values('Kaïrâta-vînâ');
insert into Instruments (Name) values('Kalimba');
insert into Instruments (Name) values('Kamalen kòni');
insert into Instruments (Name) values('Kamanja');
insert into Instruments (Name) values('Kandang indien');
insert into Instruments (Name) values('Kânih ');
insert into Instruments (Name) values('Kankangui ');
insert into Instruments (Name) values('Kanoon');
insert into Instruments (Name) values('Kanoun ');
insert into Instruments (Name) values('Kantele ');
insert into Instruments (Name) values('Kao kao javanais');
insert into Instruments (Name) values('Kara ');
insert into Instruments (Name) values('Karabid');
insert into Instruments (Name) values('Karkabet');
insert into Instruments (Name) values('Karna');
insert into Instruments (Name) values('Kass ');
insert into Instruments (Name) values('Kasso ');
insert into Instruments (Name) values('Kattyauma-vînâ');
insert into Instruments (Name) values('Kaval ');
insert into Instruments (Name) values('Kayamb ');
insert into Instruments (Name) values('Kazoo');
insert into Instruments (Name) values('Kemaçe ');
insert into Instruments (Name) values('Kemângeh à gouz');
insert into Instruments (Name) values('Kemângeh-roumy');
insert into Instruments (Name) values('Kena ');
insert into Instruments (Name) values('Kesbate ');
insert into Instruments (Name) values('Kese kese');
insert into Instruments (Name) values('Keseng keseng');
insert into Instruments (Name) values('Kétipoeng ');
insert into Instruments (Name) values('Kétjapi');
insert into Instruments (Name) values('Kharatala');
insert into Instruments (Name) values('Khên ');
insert into Instruments (Name) values('Khol');
insert into Instruments (Name) values('Khoradah');
insert into Instruments (Name) values('Khurdra kattyauna-vînâ');
insert into Instruments (Name) values('Kîn');
insert into Instruments (Name) values('Kin-kon');
insert into Instruments (Name) values('Kinan ');
insert into Instruments (Name) values('King');
insert into Instruments (Name) values('Kinnari-vînâ');
insert into Instruments (Name) values('Kinnery');
insert into Instruments (Name) values('Kîringie ');
insert into Instruments (Name) values('Kissar ');
insert into Instruments (Name) values('Klaxon');
insert into Instruments (Name) values('Klentony');
insert into Instruments (Name) values('Koant-tsé ');
insert into Instruments (Name) values('Koholo ');
insert into Instruments (Name) values('Kokiou ');
insert into Instruments (Name) values('Kònkòni');
insert into Instruments (Name) values('Kora');
insert into Instruments (Name) values('Kotek');
insert into Instruments (Name) values('Koto ');
insert into Instruments (Name) values('Kou');
insert into Instruments (Name) values('Koundyeh');
insert into Instruments (Name) values('Kousser');
insert into Instruments (Name) values('Kpanouhoun');
insert into Instruments (Name) values('Kpézin');
insert into Instruments (Name) values('Kuitra ');
insert into Instruments (Name) values('Kulintang ');
insert into Instruments (Name) values('Kunjerry');
insert into Instruments (Name) values('Langeleik ');
insert into Instruments (Name) values('Lapa');
insert into Instruments (Name) values('Laya bansi');
insert into Instruments (Name) values('Lira da braccio');
insert into Instruments (Name) values('Lithophone');
insert into Instruments (Name) values('Lituus');
insert into Instruments (Name) values('Lo');
insert into Instruments (Name) values('Lo kou ');
insert into Instruments (Name) values('Lokombi ');
insert into Instruments (Name) values('Loure');
insert into Instruments (Name) values('Lu tchun');
insert into Instruments (Name) values('Lung-tao-ty');
insert into Instruments (Name) values('Luth');
insert into Instruments (Name) values('Lyre ');
insert into Instruments (Name) values('Lyro-guitare ');
insert into Instruments (Name) values('Lyrone');
insert into Instruments (Name) values('Ma-ca-doi');
insert into Instruments (Name) values('Madiumba ');
insert into Instruments (Name) values('Magondi');
insert into Instruments (Name) values('Magrouna');
insert into Instruments (Name) values('Maha-mandira');
insert into Instruments (Name) values('Mahati-vînâ');
insert into Instruments (Name) values('Mainty kely');
insert into Instruments (Name) values('Malakat');
insert into Instruments (Name) values('Mandira ');
insert into Instruments (Name) values('Mandoline');
insert into Instruments (Name) values('Mandore');
insert into Instruments (Name) values('Mandurria ');
insert into Instruments (Name) values('Manichordion');
insert into Instruments (Name) values('Maracas ');
insert into Instruments (Name) values('Maravanne ');
insert into Instruments (Name) values('Marddala');
insert into Instruments (Name) values('Marimba');
insert into Instruments (Name) values('Marouvané');
insert into Instruments (Name) values('Mattauphone');
insert into Instruments (Name) values('Mayuri');
insert into Instruments (Name) values('Mazhar ');
insert into Instruments (Name) values('Medylenara');
insert into Instruments (Name) values('Megyoung');
insert into Instruments (Name) values('Meia-lua');
insert into Instruments (Name) values('Mellophone');
insert into Instruments (Name) values('Mellotron');
insert into Instruments (Name) values('Mélodica');
insert into Instruments (Name) values('Merline');
insert into Instruments (Name) values('Métronome');
insert into Instruments (Name) values('Mezoued ');
insert into Instruments (Name) values('Mina-sarangi');
insert into Instruments (Name) values('Mirliton');
insert into Instruments (Name) values('Mizmar ');
insert into Instruments (Name) values('Mochanga');
insert into Instruments (Name) values('Mon yu');
insert into Instruments (Name) values('Moraharpa');
insert into Instruments (Name) values('Mridang');
insert into Instruments (Name) values('Mridangam');
insert into Instruments (Name) values('Muselaar ');
insert into Instruments (Name) values('Musette');
insert into Instruments (Name) values('Muscal');
insert into Instruments (Name) values('Nacaire');
insert into Instruments (Name) values('Nadeshvara-vînà');
insert into Instruments (Name) values('Nafir');
insert into Instruments (Name) values('Nagara ');
insert into Instruments (Name) values('Nagelgeige Allemagne');
insert into Instruments (Name) values('Nagelharmonica');
insert into Instruments (Name) values('Nagharats ');
insert into Instruments (Name) values('Naï');
insert into Instruments (Name) values('Nanga');
insert into Instruments (Name) values('Napura');
insert into Instruments (Name) values('Nay');
insert into Instruments (Name) values('Néo-cor');
insert into Instruments (Name) values('Nhac');
insert into Instruments (Name) values('Nicolo');
insert into Instruments (Name) values('Nihoîhagi');
insert into Instruments (Name) values('Nimfali');
insert into Instruments (Name) values('Nira');
insert into Instruments (Name) values('Nixenharfe');
insert into Instruments (Name) values('Nkwanga');
insert into Instruments (Name) values('Noordische balk');
insert into Instruments (Name) values('Nyâstaranga');
insert into Instruments (Name) values('Nyckelharpa ');
insert into Instruments (Name) values('Ocarina');
insert into Instruments (Name) values('Ocean drum');
insert into Instruments (Name) values('Octobasse');
insert into Instruments (Name) values('Octoblock');
insert into Instruments (Name) values('Olifant');
insert into Instruments (Name) values('Ombi');
insert into Instruments (Name) values('Omerti');
insert into Instruments (Name) values('Omni');
insert into Instruments (Name) values('Ondes Martenot');
insert into Instruments (Name) values('Ongo ');
insert into Instruments (Name) values('Ophicléide');
insert into Instruments (Name) values('Organistrum');
insert into Instruments (Name) values('Orgue');
insert into Instruments (Name) values('Orgue numérique');
insert into Instruments (Name) values('Orgue de Barbarie');
insert into Instruments (Name) values('Orphéon');
insert into Instruments (Name) values('Orphéoron');
insert into Instruments (Name) values('Orphica');
insert into Instruments (Name) values('Ottavino');
insert into Instruments (Name) values('Oud ');
insert into Instruments (Name) values('Oukazasio');
insert into Instruments (Name) values('Oukpwé');
insert into Instruments (Name) values('Pakay');
insert into Instruments (Name) values('Pakhâwaj');
insert into Instruments (Name) values('Pandeiro');
insert into Instruments (Name) values('Pandereta');
insert into Instruments (Name) values('Pandore');
insert into Instruments (Name) values('Pandura');
insert into Instruments (Name) values('Pandurina');
insert into Instruments (Name) values('Pang tsé');
insert into Instruments (Name) values('Patola');
insert into Instruments (Name) values('Pedal steel');
insert into Instruments (Name) values('Pee ');
insert into Instruments (Name) values('Pennywhistle');
insert into Instruments (Name) values('Percuphone');
insert into Instruments (Name) values('Phorminx');
insert into Instruments (Name) values('Pi-li ');
insert into Instruments (Name) values('Piano');
insert into Instruments (Name) values('Piano à queue');
insert into Instruments (Name) values('Piano à tangentes');
insert into Instruments (Name) values('Piano droit');
insert into Instruments (Name) values('Piano-forte');
insert into Instruments (Name) values('Pib-gorn');
insert into Instruments (Name) values('Pibrock');
insert into Instruments (Name) values('Piccolo');
insert into Instruments (Name) values('Pifferta ');
insert into Instruments (Name) values('Pipa');
insert into Instruments (Name) values('Planche à laver');
insert into Instruments (Name) values('Pochette de maître à danser');
insert into Instruments (Name) values('Poun-goun');
insert into Instruments (Name) values('Psaltérion');
insert into Instruments (Name) values('Puïli ');
insert into Instruments (Name) values('Pung');
insert into Instruments (Name) values('Pungi ');
insert into Instruments (Name) values('Pyrophone');
insert into Instruments (Name) values('Q-Chord ');
insert into Instruments (Name) values('Qanun');
insert into Instruments (Name) values('Qaraqebs');
insert into Instruments (Name) values('Qarnay ');
insert into Instruments (Name) values('Qilaut ');
insert into Instruments (Name) values('Qin ');
insert into Instruments (Name) values('Quena');
insert into Instruments (Name) values('Quinterna ');
insert into Instruments (Name) values('Quinton');
insert into Instruments (Name) values('Rabâb ');
insert into Instruments (Name) values('Rajiok ');
insert into Instruments (Name) values('Rasarani vina ');
insert into Instruments (Name) values('Rauschpfeife');
insert into Instruments (Name) values('Ravanastron');
insert into Instruments (Name) values('ReacTable');
insert into Instruments (Name) values('Rébana ');
insert into Instruments (Name) values('Rebec ');
insert into Instruments (Name) values('Régale');
insert into Instruments (Name) values('Rek ');
insert into Instruments (Name) values('Repinique');
insert into Instruments (Name) values('Rhombe ');
insert into Instruments (Name) values('Riqq ');
insert into Instruments (Name) values('Romouze');
insert into Instruments (Name) values('Roudadar ');
insert into Instruments (Name) values('Roulèr');
insert into Instruments (Name) values('Rovana');
insert into Instruments (Name) values('Rudra-vina');
insert into Instruments (Name) values('Sabar');
insert into Instruments (Name) values('Sacqueboute ');
insert into Instruments (Name) values('Sagat ');
insert into Instruments (Name) values('Salamouri ');
insert into Instruments (Name) values('Salpinx ');
insert into Instruments (Name) values('Sambucca');
insert into Instruments (Name) values('San-heen');
insert into Instruments (Name) values('Sânâi');
insert into Instruments (Name) values('Sangé');
insert into Instruments (Name) values('Santir');
insert into Instruments (Name) values('Santour');
insert into Instruments (Name) values('Sanyogi');
insert into Instruments (Name) values('Sanza ');
insert into Instruments (Name) values('Sarala-bensi');
insert into Instruments (Name) values('Sârangî ');
insert into Instruments (Name) values('Sarciros');
insert into Instruments (Name) values('Sarod');
insert into Instruments (Name) values('Sarou ');
insert into Instruments (Name) values('Sarrussophone');
insert into Instruments (Name) values('Satârâ');
insert into Instruments (Name) values('Sato ');
insert into Instruments (Name) values('Saung ');
insert into Instruments (Name) values('Saw dorang ');
insert into Instruments (Name) values('Saw-duang');
insert into Instruments (Name) values('Saw-tai');
insert into Instruments (Name) values('Saxhorn');
insert into Instruments (Name) values('Saxhorn alto');
insert into Instruments (Name) values('Saxophone');
insert into Instruments (Name) values('Saxophone alto');
insert into Instruments (Name) values('Saxophone baryton');
insert into Instruments (Name) values('Saxophone basse');
insert into Instruments (Name) values('Saxophone contrebasse');
insert into Instruments (Name) values('Saxophone sopranino');
insert into Instruments (Name) values('Saxophone sopranissimo');
insert into Instruments (Name) values('Saxophone soprano');
insert into Instruments (Name) values('Saxophone ténor');
insert into Instruments (Name) values('Saxotromba');
insert into Instruments (Name) values('Saz ');
insert into Instruments (Name) values('Schalmey ');
insert into Instruments (Name) values('Schiguene ');
insert into Instruments (Name) values('Schiti-gekkin');
insert into Instruments (Name) values('Schlagzither');
insert into Instruments (Name) values('Scho');
insert into Instruments (Name) values('Schofar');
insert into Instruments (Name) values('Schoko');
insert into Instruments (Name) values('Schounga');
insert into Instruments (Name) values('Scie musicale');
insert into Instruments (Name) values('Sciotang');
insert into Instruments (Name) values('Seaou-po ');
insert into Instruments (Name) values('Selantan');
insert into Instruments (Name) values('Selompret');
insert into Instruments (Name) values('Serdam');
insert into Instruments (Name) values('Serinette');
insert into Instruments (Name) values('Serpent');
insert into Instruments (Name) values('Setâr');
insert into Instruments (Name) values('Shakuhachi');
insert into Instruments (Name) values('Shamisen');
insert into Instruments (Name) values('Sharadiya-vina');
insert into Instruments (Name) values('Shekere');
insert into Instruments (Name) values('Shehnai');
insert into Instruments (Name) values('Sheng ');
insert into Instruments (Name) values('Shophar');
insert into Instruments (Name) values('Showktica-vina');
insert into Instruments (Name) values('Shuang-kin');
insert into Instruments (Name) values('Siao');
insert into Instruments (Name) values('Sifflet');
insert into Instruments (Name) values('Sigou-mbarva');
insert into Instruments (Name) values('Sigou-nihou');
insert into Instruments (Name) values('Siku ');
insert into Instruments (Name) values('Silbote');
insert into Instruments (Name) values('Sinbi');
insert into Instruments (Name) values('Siotantka ');
insert into Instruments (Name) values('Sira');
insert into Instruments (Name) values('Sistre ');
insert into Instruments (Name) values('Sitar ');
insert into Instruments (Name) values('Sodina, sody, soly, antsoly');
insert into Instruments (Name) values('Sona');
insert into Instruments (Name) values('Sonaja');
insert into Instruments (Name) values('Sorna');
insert into Instruments (Name) values('Soubassophone');
insert into Instruments (Name) values('Soudzou');
insert into Instruments (Name) values('Souffârrah');
insert into Instruments (Name) values('Soug');
insert into Instruments (Name) values('Souma-koto ');
insert into Instruments (Name) values('Soung-king');
insert into Instruments (Name) values('Sounnaïa ');
insert into Instruments (Name) values('Souqqarah');
insert into Instruments (Name) values('Sourdine');
insert into Instruments (Name) values('Sousounou');
insert into Instruments (Name) values('Spitzharfe');
insert into Instruments (Name) values('Sringa');
insert into Instruments (Name) values('Sruti-vina');
insert into Instruments (Name) values('Stamentien-pfeiffe');
insert into Instruments (Name) values('Steel-drum');
insert into Instruments (Name) values('Stick');
insert into Instruments (Name) values('Stock-horn');
insert into Instruments (Name) values('Stopf-trumpet');
insert into Instruments (Name) values('Streich-zither ');
insert into Instruments (Name) values('Stretch machine');
insert into Instruments (Name) values('Suka');
insert into Instruments (Name) values('Suling');
insert into Instruments (Name) values('Suona');
insert into Instruments (Name) values('Sur-bahara ');
insert into Instruments (Name) values('Sur-vâhâra ');
insert into Instruments (Name) values('Sur-vina ');
insert into Instruments (Name) values('Surdo');
insert into Instruments (Name) values('Swedish bagpipe ');
insert into Instruments (Name) values('Synthétiseur');
insert into Instruments (Name) values('Syntophone');
insert into Instruments (Name) values('Sze-hou-hsien');
insert into Instruments (Name) values('Ta huang hou kin ');
insert into Instruments (Name) values('Taakan');
insert into Instruments (Name) values('Taarija');
insert into Instruments (Name) values('Tablâ ');
insert into Instruments (Name) values('Tablat');
insert into Instruments (Name) values('Taiko ');
insert into Instruments (Name) values('Taïsene');
insert into Instruments (Name) values('Taki-koto');
insert into Instruments (Name) values('Talain');
insert into Instruments (Name) values('Tam-tam');
insert into Instruments (Name) values('Tama ');
insert into Instruments (Name) values('Tamborim ');
insert into Instruments (Name) values('Tambour ');
insert into Instruments (Name) values('Tambour boulghary ');
insert into Instruments (Name) values('Tambourin ');
insert into Instruments (Name) values('Tambûr');
insert into Instruments (Name) values('Tan-tan');
insert into Instruments (Name) values('Tao-kou');
insert into Instruments (Name) values('Tarogato');
insert into Instruments (Name) values('Tapan ');
insert into Instruments (Name) values('Târ ');
insert into Instruments (Name) values('Tarambouka');
insert into Instruments (Name) values('Tarole');
insert into Instruments (Name) values('Tarqa ');
insert into Instruments (Name) values('Tasa');
insert into Instruments (Name) values('Tashepoto ');
insert into Instruments (Name) values('Tatchoota');
insert into Instruments (Name) values('Tawaya ');
insert into Instruments (Name) values('Tbal ');
insert into Instruments (Name) values('Tchang-kou ');
insert into Instruments (Name) values('Tché ');
insert into Instruments (Name) values('Tchengue ');
insert into Instruments (Name) values('Tchogor');
insert into Instruments (Name) values('Tchong');
insert into Instruments (Name) values('Tchong-tou');
insert into Instruments (Name) values('Tchou');
insert into Instruments (Name) values('Té-tchong ');
insert into Instruments (Name) values('Tebashoul ');
insert into Instruments (Name) values('Tebilats');
insert into Instruments (Name) values('Tebloun');
insert into Instruments (Name) values('Telharmonium ');
insert into Instruments (Name) values('Tembour ');
insert into Instruments (Name) values('Tenora ');
insert into Instruments (Name) values('Terab-enguiz');
insert into Instruments (Name) values('Terpodion ');
insert into Instruments (Name) values('Terr');
insert into Instruments (Name) values('Tet-jer ');
insert into Instruments (Name) values('Thar');
insert into Instruments (Name) values('Thari ');
insert into Instruments (Name) values('Théorbe');
insert into Instruments (Name) values('Thérémine ');
insert into Instruments (Name) values('Thumgo-tuapan');
insert into Instruments (Name) values('Thurnerhorn');
insert into Instruments (Name) values('Ti-kin ');
insert into Instruments (Name) values('Tien-kou ');
insert into Instruments (Name) values('Tilinca ');
insert into Instruments (Name) values('Timba');
insert into Instruments (Name) values('Timbale');
insert into Instruments (Name) values('Timbales, et timbalitos et timbalon');
insert into Instruments (Name) values('Timple');
insert into Instruments (Name) values('Tiple');
insert into Instruments (Name) values('Tjé-tjé ');
insert into Instruments (Name) values('Tohona');
insert into Instruments (Name) values('Tombah ');
insert into Instruments (Name) values('Tombak ');
insert into Instruments (Name) values('To rung ');
insert into Instruments (Name) values('Toumourah');
insert into Instruments (Name) values('Tournebout');
insert into Instruments (Name) values('Tourti');
insert into Instruments (Name) values('Toutsoumi ');
insert into Instruments (Name) values('Trawanga');
insert into Instruments (Name) values('Tres');
insert into Instruments (Name) values('Triangle');
insert into Instruments (Name) values('Tritantri-vina ');
insert into Instruments (Name) values('Tritare');
insert into Instruments (Name) values('Troccola ');
insert into Instruments (Name) values('Trombone à coulisse');
insert into Instruments (Name) values('Trombone à pistons');
insert into Instruments (Name) values('Trompe de chasse');
insert into Instruments (Name) values('Trompe suisse');
insert into Instruments (Name) values('Trompette de mail coach');
insert into Instruments (Name) values('Trompette marine');
insert into Instruments (Name) values('Trompette médiévale');
insert into Instruments (Name) values('Tseng');
insert into Instruments (Name) values('Tsikadraha');
insert into Instruments (Name) values('Tsou-kou');
insert into Instruments (Name) values('Tsou toung hou-kin');
insert into Instruments (Name) values('Tsouma-koto');
insert into Instruments (Name) values('Tsouzoumi');
insert into Instruments (Name) values('Tuba');
insert into Instruments (Name) values('Tuba corva');
insert into Instruments (Name) values('Tubilattes');
insert into Instruments (Name) values('Tubri');
insert into Instruments (Name) values('Tubular bells');
insert into Instruments (Name) values('Tumburu-vina');
insert into Instruments (Name) values('Turi');
insert into Instruments (Name) values('Turr');
insert into Instruments (Name) values('Txalaparta ');
insert into Instruments (Name) values('Txanbela');
insert into Instruments (Name) values('Txirula ');
insert into Instruments (Name) values('Txistu ');
insert into Instruments (Name) values('Ty');
insert into Instruments (Name) values('Tympanon');
insert into Instruments (Name) values('Uilacapitztli');
insert into Instruments (Name) values('Ukeke-laau ');
insert into Instruments (Name) values('Ukulélé ');
insert into Instruments (Name) values('Uliuli ');
insert into Instruments (Name) values('Utricularium');
insert into Instruments (Name) values('Udu');
insert into Instruments (Name) values('Valiha toritenany ');
insert into Instruments (Name) values('Vançali ');
insert into Instruments (Name) values('Venu ');
insert into Instruments (Name) values('Veuze ');
insert into Instruments (Name) values('Vibraphone');
insert into Instruments (Name) values('Vibraslap, fouet vobrant');
insert into Instruments (Name) values('Vièle');
insert into Instruments (Name) values('Vielle à roue');
insert into Instruments (Name) values('Vihuela');
insert into Instruments (Name) values('Villancoyel');
insert into Instruments (Name) values('Vînâ ');
insert into Instruments (Name) values('Vioarã cu goarnã');
insert into Instruments (Name) values('Viole');
insert into Instruments (Name) values('Viole de gambe');
insert into Instruments (Name) values('Violon');
insert into Instruments (Name) values('Violon à pavillon ');
insert into Instruments (Name) values('Violon alto');
insert into Instruments (Name) values('Violon savart');
insert into Instruments (Name) values('Violoncelle');
insert into Instruments (Name) values('Violone');
insert into Instruments (Name) values('Vipancia vina');
insert into Instruments (Name) values('Virginal ');
insert into Instruments (Name) values('Voix');
insert into Instruments (Name) values('Wakrapuku ');
insert into Instruments (Name) values('Wambée');
insert into Instruments (Name) values('Wangong');
insert into Instruments (Name) values('Waterphone');
insert into Instruments (Name) values('Whit-horn ');
insert into Instruments (Name) values('Wistaka ');
insert into Instruments (Name) values('Wood-block');
insert into Instruments (Name) values('Xaphoon ');
insert into Instruments (Name) values('Xeremia');
insert into Instruments (Name) values('Xiao');
insert into Instruments (Name) values('Xun ');
insert into Instruments (Name) values('Xylophone');
insert into Instruments (Name) values('Yabara');
insert into Instruments (Name) values('Yakoumakoto ');
insert into Instruments (Name) values('Yang');
insert into Instruments (Name) values('Yang-kin');
insert into Instruments (Name) values('Yo');
insert into Instruments (Name) values('Yotsu-dake ');
insert into Instruments (Name) values('You-kin');
insert into Instruments (Name) values('Youkoulélé, voir ukulélé');
insert into Instruments (Name) values('Yun-lo ');
insert into Instruments (Name) values('Zampogna simplice ');
insert into Instruments (Name) values('Zampoña');
insert into Instruments (Name) values('Zamr-el-kébyr ');
insert into Instruments (Name) values('Zamr-el-soghair ');
insert into Instruments (Name) values('Zanza ');
insert into Instruments (Name) values('Zarb ');
insert into Instruments (Name) values('Zithera ');
insert into Instruments (Name) values('Zokra');
insert into Instruments (Name) values('Zongora ');
insert into Instruments (Name) values('Zourna ');
insert into Instruments (Name) values('Zummârah arbaouïa ');
insert into Instruments (Name) values('Zummârah khamsaouïa ');
insert into Instruments (Name) values('Zummârah settaouïa ');
insert into Instruments (Name) values('Zummârah sabaouïa ');