//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrouveUnBand.Models
{
    public partial class Band
    {
        public Band()
        {
            this.Genres = new HashSet<Genre>();
            this.Users = new HashSet<User>();
            this.Events = new HashSet<Event>();
        }
    
        public int Band_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
    
}
