//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrouveUnBand.Models
{
    public partial class Event
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string EventLocation { get; set; }
        public string EventAddress { get; set; }
        public string EventCity { get; set; }
        public System.DateTime EventDate { get; set; }
        public string EventMaxAudience { get; set; }
        public float EventSalary { get; set; }
        public string EventGender { get; set; }
        public Nullable<int> EventStageSize { get; set; }
    }
    
}
