//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrouveUnBand.Models
{
    public partial class Event
    {
        public Event()
        {
            this.Bands = new HashSet<Band>();
            this.Genres = new HashSet<Genre>();
            this.Users = new HashSet<User>();
        }
    
        public int Event_ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public System.DateTime EventDate { get; set; }
        public int MaxAudience { get; set; }
        public float Salary { get; set; }
        public string StageSize { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Creator_ID { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
    
}
