//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrouveUnBand.Models
{
    public partial class Genre
    {
        public Genre()
        {
            this.Sub_Genre = new HashSet<Sub_Genres>();
        }

        public ICollection<Sub_Genres> Sub_Genre { get; set; }

        public String Name { get; set; }
        public int GenreId { get; set; }
    }
    
}
