//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrouveUnBand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public Instrument()
        {
            this.Musicians = new HashSet<Musician>();
        }
    
        public int InstrumentId { get; set; }
        public string Name { get; set; }
        public DateTime date_putin { get; set; }
    
        public virtual ICollection<Musician> Musicians { get; set; }
    }
}
