//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrouveUnBand.Models
{
    public partial class Join_Musician_Instrument
    {
        public int MusicianId { get; set; }
        public int InstrumentId { get; set; }
        public int Skills { get; set; }
 
        public virtual Instrument Instrument { get; set; }
        public virtual Musician Musician { get; set; }
    }
    
}
