//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace TrouveUnBand.Models
{
    public partial class TrouveUnBandEntities : DbContext
    {
        public TrouveUnBandEntities()
            : base("name=TrouveUnBandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Advert> Adverts { get; set; }
        public DbSet<Band> Bands { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Instrument> Instruments { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Users_Instruments> Users_Instruments { get; set; }
    }
}
