//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrouveUnBand.Models
{
    public partial class Musician
    {
        public Musician()
        {
            this.Join_Musician_Instrument = new HashSet<Join_Musician_Instrument>();
            this.Bands = new HashSet<Band>();
            this.Sub_Genres = new HashSet<Sub_Genres>();
        }
    
        public int MusicianId { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Join_Musician_Instrument> Join_Musician_Instrument { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<Sub_Genres> Sub_Genres { get; set; }
    }
}
