//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrouveUnBand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musician
    {
        public Musician()
        {
            this.Bands = new HashSet<Band>();
            this.Genres = new HashSet<Genre>();
            this.Instruments = new HashSet<Instrument>();
        }
    
        public int MusicianId { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<Instrument> Instruments { get; set; }
    }
}
