//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrouveUnBand.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Genres
    {
        public int Sub_GenreId { get; set; }
        public int GenreId { get; set; }
        public string Name { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Band> Bands { get; set; }
        public virtual ICollection<Musician> Musicians { get; set; }
    }
}
