//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrouveUnBand.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrouveUnBandEntities1 : DbContext
    {
        public TrouveUnBandEntities1()
            : base("name=TrouveUnBandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Band> Bands { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Instrument> Instruments { get; set; }
        public DbSet<Join_Musician_Instrument> Join_Musician_Instrument { get; set; }
        public DbSet<Musician> Musicians { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Sub_Genres> Sub_Genres { get; set; }
        public DbSet<Evenement> Evenements { get; set; }
    }
}
