//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace TrouveUnBand.Models
{
    public partial class Users_Instruments
    {
        public int User_ID { get; set; }
        public int Instrument_ID { get; set; }
        public int Skills { get; set; }
    
        public virtual Instrument Instrument { get; set; }
        public virtual User User { get; set; }
    }
    
}
